# config.py
STORAGEACCOUNTURL = "YOUR AZURE STORAGE ACCOUNT URL"
STORAGEACCOUNTKEY = "YOUR AZURE STORAGE ACCOUNT KEY"
CONNECTIONSTRING = "YOUR AZURE CONNECTION STRING"
CONTAINERNAME = "trip-connections"
ACCOUNTNAME = "YOU AZURE ACCOUNT NAME"